# Dockerfile to allow running as GH Codespace only - paired with .devcontainer.json to complete setup
FROM mcr.microsoft.com/devcontainers/python:1-3.10-bullseye
RUN apt-get update && apt-get install -y xz-utils
